"""pacientes, vínculos e invitaciones

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-30 18:19:20.510091

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patients",
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_patients_created_by_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_patients_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_patients")),
        sa.UniqueConstraint("owner_user_id", name=op.f("uq_patients_owner_user_id")),
    )
    op.create_index("ix_patients_created_at_id", "patients", ["created_at", "id"], unique=False)
    op.create_table(
        "care_links",
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("caregiver_user_id", sa.Uuid(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["caregiver_user_id"],
            ["users.id"],
            name=op.f("fk_care_links_caregiver_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_care_links_patient_id_patients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["revoked_by_user_id"],
            ["users.id"],
            name=op.f("fk_care_links_revoked_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_care_links")),
        sa.UniqueConstraint(
            "patient_id", "caregiver_user_id", name=op.f("uq_care_links_patient_id")
        ),
    )
    op.create_index(
        "ix_care_links_caregiver_active",
        "care_links",
        ["caregiver_user_id", "active"],
        unique=False,
    )
    op.create_table(
        "caregiver_invitations",
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("used_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_caregiver_invitations_created_by_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_caregiver_invitations_patient_id_patients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["used_by_user_id"],
            ["users.id"],
            name=op.f("fk_caregiver_invitations_used_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_caregiver_invitations")),
        sa.UniqueConstraint("code_hash", name=op.f("uq_caregiver_invitations_code_hash")),
    )
    op.create_index(
        op.f("ix_caregiver_invitations_patient_id"),
        "caregiver_invitations",
        ["patient_id"],
        unique=False,
    )
    op.add_column("consent_events", sa.Column("subject_patient_id", sa.Uuid(), nullable=True))
    op.create_index(
        "ix_consent_events_patient_purpose",
        "consent_events",
        ["subject_patient_id", "purpose", "created_at"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_consent_events_subject_patient_id_patients"),
        "consent_events",
        "patients",
        ["subject_patient_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # Alembic no detecta CHECK nuevos: un único titular por decisión.
    op.create_check_constraint(
        op.f("ck_consent_events_single_subject"),
        "consent_events",
        "(subject_user_id IS NULL) <> (subject_patient_id IS NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_consent_events_single_subject"), "consent_events", type_="check")
    op.drop_constraint(
        op.f("fk_consent_events_subject_patient_id_patients"), "consent_events", type_="foreignkey"
    )
    op.drop_index("ix_consent_events_patient_purpose", table_name="consent_events")
    op.drop_column("consent_events", "subject_patient_id")
    op.drop_index(op.f("ix_caregiver_invitations_patient_id"), table_name="caregiver_invitations")
    op.drop_table("caregiver_invitations")
    op.drop_index("ix_care_links_caregiver_active", table_name="care_links")
    op.drop_table("care_links")
    op.drop_index("ix_patients_created_at_id", table_name="patients")
    op.drop_table("patients")
    # ### end Alembic commands ###
